/**
 * Structured data (schema.org JSON-LD) and shared metadata values.
 * Everything here derives from config.ts and subjects.ts so it can never drift from the page copy.
 */
import { SERVICES, SITE, type Service } from "./config";
import { subjectPath, subjectService, type Subject } from "./subjects";
import { siteOrigin } from "./site-url";

export const SEO = {
  /** Shown in <title> on the home page. Under 60 characters. */
  homeTitle: "GCSE, A-level, UCAT & Medicine Tutor | Preethi Amudhan",
  homeDescription:
    "One-to-one online tutoring in any GCSE or A-level subject, UCAT prep and medical school applications from a final-year medical student. From £30/hr.",
  keywords: [
    "online tutor",
    "GCSE tutor",
    "A-level tutor",
    "chemistry tutor",
    "biology tutor",
    "maths tutor",
    "UCAT tutor",
    "medical school application help",
    "medicine interview coaching",
    "Norwich tutor",
    "tutor in Norwich",
    "medical student tutor",
  ],
  /** Date the content was last materially revised. Used in the sitemap instead of the build time. */
  contentUpdated: new Date("2026-09-03"),
  /** Date the terms and privacy notice were last revised. */
  legalUpdated: new Date("2026-09-03"),
  /** Social share image, generated by app/opengraph-image.tsx. Pages that declare their own openGraph block must list it explicitly. */
  shareImage: "/opengraph-image",
} as const;

/**
 * Open Graph + Twitter metadata for one page. Next replaces, rather than merges, a page's
 * `openGraph` object, so every page that sets one must restate the site-wide fields and image.
 */
export function pageSocial(path: string, title: string, description: string) {
  return {
    openGraph: { type: "website" as const, url: path, title, description, siteName: SITE.name, locale: "en_GB", images: [SEO.shareImage] },
    twitter: { card: "summary_large_image" as const, title, description, images: [SEO.shareImage] },
  };
}

export function absoluteUrl(path = "/"): string {
  return new URL(path, siteOrigin()).toString();
}

const ORG_ID = () => `${siteOrigin()}/#organization`;
const PERSON_ID = () => `${siteOrigin()}/#tutor`;
const WEBSITE_ID = () => `${siteOrigin()}/#website`;

function offer(service: Service) {
  return {
    "@type": "Offer",
    name: service.name,
    description: service.description,
    price: (service.pricePence / 100).toFixed(2),
    priceCurrency: "GBP",
    availability: "https://schema.org/InStock",
    url: absoluteUrl(`/book?service=${service.id}`),
  };
}

export function tutorPerson() {
  return {
    "@type": "Person",
    "@id": PERSON_ID(),
    name: SITE.tutorName,
    jobTitle: "Private tutor and final-year medical student",
    email: SITE.contactEmail,
    url: siteOrigin(),
    worksFor: { "@id": ORG_ID() },
    alumniOf: [{ "@type": "EducationalOrganization", name: "Sir Isaac Newton Sixth Form" }],
    affiliation: { "@type": "CollegeOrUniversity", name: "University of East Anglia" },
    knowsAbout: ["GCSE", "GCSE Maths", "GCSE Biology", "GCSE Chemistry", "GCSE Physics", "A-level", "A-level Biology", "A-level Chemistry", "A-level Maths", "UCAT", "Medical school applications"],
    address: { "@type": "PostalAddress", addressLocality: "Norwich", addressCountry: "GB" },
  };
}

export function organisation() {
  return {
    // Not a LocalBusiness: there is no public street address, and Google expects one for that type.
    "@type": "EducationalOrganization",
    "@id": ORG_ID(),
    name: SITE.name,
    url: siteOrigin(),
    image: absoluteUrl("/opengraph-image"),
    logo: absoluteUrl("/apple-icon"),
    description: SEO.homeDescription,
    email: SITE.contactEmail,
    ...(SITE.showPhone ? { telephone: SITE.phoneE164 } : {}),
    founder: { "@id": PERSON_ID() },
    employee: { "@id": PERSON_ID() },
    address: { "@type": "PostalAddress", addressLocality: "Norwich", addressRegion: "Norfolk", addressCountry: "GB" },
    areaServed: { "@type": "Country", name: "United Kingdom" },
    priceRange: "£30 - £35 per hour",
    currenciesAccepted: "GBP",
    paymentAccepted: "Credit card, Debit card",
    openingHoursSpecification: [
      { "@type": "OpeningHoursSpecification", dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], opens: "17:00", closes: "21:00" },
      { "@type": "OpeningHoursSpecification", dayOfWeek: ["Saturday", "Sunday"], opens: "09:00", closes: "17:00" },
    ],
    makesOffer: SERVICES.map(offer),
  };
}

export function website() {
  return {
    "@type": "WebSite",
    "@id": WEBSITE_ID(),
    url: siteOrigin(),
    name: SITE.name,
    inLanguage: "en-GB",
    publisher: { "@id": ORG_ID() },
  };
}

/** FAQ node for a page, identified as `<page>#faq` so the page's WebPage node can point at it. */
export function faqPage(items: { q: string; a: string }[], path: string) {
  return {
    "@type": "FAQPage",
    "@id": `${absoluteUrl(path)}#faq`,
    mainEntity: items.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  };
}

export function breadcrumbs(items: { name: string; path: string }[]) {
  return {
    "@type": "BreadcrumbList",
    itemListElement: items.map((it, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: it.name,
      item: absoluteUrl(it.path),
    })),
  };
}

/** Page-specific name so the two medicine pages, which sell one service, do not emit identical entities. */
function subjectServiceName(subject: Subject): string {
  return subject.slug === "medical-school-applications" ? "Medical school application coaching" : `${subject.title} tutoring`;
}

export function subjectServiceSchema(subject: Subject) {
  const service = subjectService(subject);
  const name = subjectServiceName(subject);
  return {
    "@type": "Service",
    "@id": `${absoluteUrl(subjectPath(subject))}#service`,
    name,
    serviceType: name,
    description: subject.metaDescription,
    url: absoluteUrl(subjectPath(subject)),
    provider: { "@id": ORG_ID() },
    areaServed: { "@type": "Country", name: "United Kingdom" },
    availableChannel: { "@type": "ServiceChannel", serviceUrl: absoluteUrl("/book"), name: "Online via Google Meet" },
    audience: { "@type": "EducationalAudience", educationalRole: "student" },
    offers: { ...offer(service), name },
  };
}

export function webPage(path: string, name: string, description: string, opts: { faq?: boolean } = {}) {
  return {
    "@type": "WebPage",
    "@id": absoluteUrl(path),
    url: absoluteUrl(path),
    name,
    description,
    isPartOf: { "@id": WEBSITE_ID() },
    about: { "@id": ORG_ID() },
    inLanguage: "en-GB",
    ...(opts.faq ? { mainEntity: { "@id": `${absoluteUrl(path)}#faq` } } : {}),
  };
}

/** Wraps any number of schema nodes in one @graph document. */
export function graph(...nodes: object[]) {
  return { "@context": "https://schema.org", "@graph": nodes };
}
